[build]
  base = "frontend"
  publish = "frontend/build"
  command = "npm install && npm run build"

[context.production.environment]
  NODE_VERSION = "16.0.0"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
